flask_app/game/routes.py
from flask import Blueprint, render_template, request, session
import base64, io
import random
from io import BytesIO
from flask_login import current_user, login_required
from ..models import User
from ..client import GameClient
from .. import bcrypt

game = Blueprint('game', __name__)
game_client = GameClient()
global global_current_score
global length
global_current_score = 0
length = len(game_client.get_game_list())

def get_b64_img(username):
    user = User.objects(username=username).first()
    if user.profile_pic is None:
        return None
    bytes_im = io.BytesIO(user.profile_pic.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image


@game.route('/hard')
@login_required
def hard(username=None):
    user = User.objects(username=username).first() if username else None
    games_lst = sorted(game_client.get_game_list(),key=lambda x:x[3])
    easy = games_lst[0:(length // 3)]
    selected_games = random.sample(easy, 2)
    session['selected_games'] = easy
    return render_template('game.html',user=current_user,game_list=selected_games,game_client=game_client,score=global_current_score)


@game.route('/medium')
@login_required
def medium(username=None):
    user = User.objects(username=username).first() if username else None
    games_lst = sorted(game_client.get_game_list(),key=lambda x:x[3])
    medium = games_lst[(length // 3):(2*length)//3]
    selected_games = random.sample(medium, 2)
    session['selected_games'] = selected_games
    return render_template('game.html',user=current_user,game_list=selected_games,game_client=game_client,score=global_current_score)

@game.route('/easy')
@login_required
def easy(username=None):
    user = User.objects(username=username).first() if username else None
    games_lst = sorted(game_client.get_game_list(),key=lambda x:x[3])
    hard = games_lst[(2*length) // 3:]
    selected_games = random.sample(hard, 2)
    session['selected_games'] = selected_games
    return render_template('game.html',user=current_user,game_list=selected_games,game_client=game_client,score=global_current_score)

@game.route('/process_selection', methods=['POST'])
def process_selection():
    selected_game_name = request.form.get('selected_game')
    
    # Retrieve the selected games from the session or another data source
    selected_games = session.get('selected_games')
    
    # Find the selected game object based on its name
    selected_game = next((game for game in selected_games if game[0] == selected_game_name), None)
    
    # Find the game that wasn't selected
    non_selected_game = [game for game in selected_games if game != selected_game]

    if selected_game:
        if selected_game[3] >= non_selected_game[0][3]:
            global global_current_score
            global_current_score += 1
            games_lst = [game for game in game_client.get_game_list() if game not in selected_games]
            session.pop('selected_games', None)
            games_lst = sorted(games_lst, key=lambda x: x[3])
            new_selected_games = random.choices(games_lst, k=2)
            session['selected_games'] = new_selected_games
            if not(current_user.highScore):
                current_user.highScore = global_current_score
            else:
                current_user.highScore = max(current_user.highScore,global_current_score)          
            return render_template('game.html',user=current_user,game_list=new_selected_games,game_client=game_client,score=global_current_score)
        else:
            session.pop('selected_games', None)
            current_user.scores.append(global_current_score)
            global_current_score = 0
            current_user.save()
            if not(current_user.highScore):
                current_user.highScore = max(max(current_user.scores),global_current_score)
            else:
                current_user.highScore = max(current_user.highScore,max(current_user.scores),global_current_score)
            current_user.save()
            return render_template('loss.html',user=current_user,lastScore=current_user.scores[-1])
    else:
        session.pop('selected_games', None)
        global_current_score = 0


@game.route('/leaderboard')
def leaderboard():
    # we need a way to iterate through each user, grabbing their highest score
    # we then can sort (in reverse) the scores and then pass it into the leaderboard html
    # the reason why we should do reverse is when we iterate through the list in the template,
    # it outputs the highest score first, and so on
    all_users = User.objects()
    user_scores = []
    for user in all_users:
        user_scores.append((user.username,get_b64_img(user.username),user.highScore if user.highScore else 0 ))
    user_scores.sort(key= lambda x: -x[2])
    return render_template('leaderboard.html',scores=user_scores)

flask_app/users/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, abort
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.utils import secure_filename
import io
import base64
from ..models import User
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm, UpdateProfilePicForm
from .. import bcrypt

users = Blueprint("users", __name__)

def get_b64_img(username):
    user = User.objects(username=username).first()
    if user.profile_pic is None:
        return None
    bytes_im = io.BytesIO(user.profile_pic.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image

@users.route('/register', methods=['GET', 'POST'])
def register_route():
    if current_user.is_authenticated: # essentially when the user is logged in we simply display the other
                                      # form of the main screen. 
        return redirect(url_for('main.index'))
    form = RegistrationForm() # getting an instance of the form. 
    if request.method == 'POST': # user has submitted the form with
        if form.validate_on_submit():
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            user = User(username=form.username.data, email=form.email.data, password=hashed_password)
            user.save()
            return redirect(url_for('users.login_route'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login_route():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.objects(username=form.username.data).first()
            if user is not None and bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('users.user_route', username=user.username))
            else:
                flash("Failed to log in!")
    return render_template('login.html', form=form)

@users.route('/user/<username>', methods=['GET', 'POST'])
@login_required
def user_route(username):
    update_username_form = UpdateUsernameForm()
    update_profile_pic_form = UpdateProfilePicForm()
    if not (current_user):
        abort(404)
    if request.method == "POST":
        if update_username_form.submit_username.data and update_username_form.validate():
            current_user.modify(username=update_username_form.username.data)
            current_user.save()
            return redirect(url_for('users.login_route'))
        if update_profile_pic_form.submit_picture.data and update_profile_pic_form.validate():
            image = update_profile_pic_form.picture.data
            filename = secure_filename(image.filename) 
            content_type = f'images/{filename[-3:]}'
            if current_user.profile_pic is None: 
                current_user.profile_pic.put(image.stream, content_type=content_type)
            else:
                current_user.profile_pic.replace(image.stream, content_type=content_type)
            current_user.save()
            return redirect(url_for('users.user_route',username=current_user.username))
    scores = current_user.scores if current_user.scores else []
    return render_template('user.html',user=current_user, 
                           update_username_form=update_username_form,
                           update_profile_pic_form=update_profile_pic_form, 
                           profile_pic_base64=get_b64_img(current_user.username), 
                           scores=scores,
                           highscore=max(scores) if scores else 0)

@users.route('/logout')
def logout_route():
    logout_user()
    return redirect(url_for('main.index'))

# def add_score_to_user(username, new_score):
#     user = User.objects(username=username).first()
#     if user:
#         user.scores.append(new_score)
#         user.save()
#         user.highScore = max(user.scores)
#         user.save()
#     else:
#         return render_template('404.html')

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{url_for('static',filename='compiled.css')}}"/>
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Higher or Lower Game</title>
</head>
<body class="bg-black">
    {% block content %}{% endblock %}
</body>
</html>

flask_app/templates/game.html
{% extends "base.html" %} 
{% block content %}
<a href="{{ url_for('main.index') }}" class="text-white bg-blue-500 hover:bg-blue-700 font-bold py-2 px-4 rounded">
    Back to Home
</a>
<header class="text-white py-4">
    <div class="container mx-auto text-center">
        {% if user %}
            <h1 class="text-3xl font-bold bg-gradient-to-r from-yellow-500 to-red-500 text-transparent bg-clip-text">Welcome, {{ user.username }}!</h1>
            <p class="mt-2 bg-gradient-to-r from-yellow-500 to-red-500 text-transparent bg-clip-text">Your current score: {{score}}</p>
            <p class="mt-2 bg-gradient-to-r from-yellow-500 to-red-500 text-transparent bg-clip-text">Your high score: {{ user.highScore }}</p>
        {% else %}
            <h1 class="text-3xl font-bold bg-gradient-to-r from-yellow-500 to-red-500 text-transparent bg-clip-text">Welcome!</h1>
            <p class="mt-2 bg-gradient-to-r from-yellow-500 to-red-500 text-transparent bg-clip-text">Your current score: {{score}}</p>
        {% endif %}
    </div>
</header>

<form action="{{ url_for('game.process_selection') }}" method="post" class="flex flex-wrap justify-center">
    {% for game in game_list %}
        <div class="bg-black p-5 border border-gray-500 rounded-xl transition duration-300 ease-in-out transform hover:-translate-y-1 hover:shadow-xl w-full md:w-1/2">
            <h3 class="text-3xl font-semibold bg-gradient-to-r from-yellow-500 to-red-500 text-transparent bg-clip-text text-center mb-3">{{ game[0] }}</h3>
            <button type="submit" name="selected_game" value="{{ game[0] }}">
                <img src="{{ game[1] }}" alt="{{ game[0] }} background image" class="rounded-xl object-cover h-80 w-full">
            </button>
        </div>
    {% endfor %}
</form>
{% endblock %}

flask_app/templates/header.html
{% extends "base.html" %} {% block header %}
<nav class="navbar flex w-full justify-between z-40">
    <a class="m-5 navlink" href="{{ url_for('main.index') }}">
        <span class="hidden sm:block">higher or lower game</span>
        <span class="block sm:hidden">Home</span>
    </a>
    {% if current_user.is_authenticated %}
    <div class="flex">
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.user_route') }}">Account</a>
        <a class="my-5 mr-5 ml-0 navlink !bg-red-400/20 hover:!bg-red-500/50 !text-red-400 hover:!text-red-300" href="{{ url_for('users.logout') }}">Logout</a>
    </div>
    {% else %}
    <div class="flex">
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.login_route') }}">Login</a>
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.register_route') }}">Register</a>
    </div>
    {% endif %}
</nav>
{% block content %}{% endblock %}{% endblock %}

flask_app/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="flex justify-center items-center min-h-screen bg-black">
    <div class="text-center">
        <h1 class="text-5xl font-bold mb-8 relative z-10">
            <span class="bg-gradient-to-r from-yellow-500 to-red-500 text-transparent bg-clip-text">Higher or Lower Game - Steam Edition</span>
        </h1>
        
        {% if current_user.is_authenticated %}
            <p class="text-2xl text-white mb-4">Welcome back, <span class="text-red-600">{{ current_user.username }}</span>!</p>
        {% endif %}
        
    
        <a href="{{ url_for('game.easy') }}" class="inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full mb-4 shadow-md">
            Start Game: Easy
        </a>
    
        <a href="{{ url_for('game.medium') }}" class="inline-block bg-yellow-600 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded-full mb-4 shadow-md">
            Start Game: Medium
        </a>
    
        <a href="{{ url_for('game.hard') }}" class="inline-block bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-full mb-4 shadow-md">
            Start Game: Hard
        </a>
        
        <!-- Show the profile button if the user is logged in -->
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('users.user_route', username=current_user.username) }}" class="inline-block bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-full mb-4 shadow-md">
            My Profile
        </a>
        {% else %}
        <!-- Show login and register buttons if the user is not logged in -->
        <div class="flex justify-center">
            <a href="{{ url_for('users.login_route') }}" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-l mr-2 shadow-md">
                Login
            </a>
            <a href="{{ url_for('users.register_route') }}" class="bg-pink-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-r shadow-md">
                Register
            </a>
        </div>
        {% endif %}
        <div class="mt-8 p-6 rounded-lg shadow-md">
            <p class="text-3xl font-bold bg-gradient-to-r from-yellow-500 to-red-500 text-transparent bg-clip-text">TO WIN SELECT THE GAME THAT YOU FEEL HAS THE MAXIMUM DOWNLOADS</p>
        </div>
    </div>    
</div>

{% endblock %}

flask_app/templates/leaderboard.html
<!-- TODO -->

{% extends "base.html" %} 
{% block content %}
<a href="{{ url_for('main.index') }}" class="text-white bg-blue-500 hover:bg-blue-700 font-bold py-2 px-4 rounded">
    Back to Home
</a>

<div class="bg-transparent shadow-md rounded-md overflow-hidden max-w-lg mx-auto mt-16">
    <div class="bg-white py-2 px-4">
        <h2 class="text-xl font-semibold text-red-600">Leaderboard</h2>
    </div>
    <ol class="divide-y divide-gray-700">
        {% for username, profile_pic, user_score in scores %}
        <li class="flex items-center justify-between py-4 px-6">
            <!-- <span class="text-green-300 text-lg font-medium">{{ loop.index }}. </span> -->
            <div class="flex items-center flex-grow">
                <h3 class="text-lg font-bold text-left text-orange-500 mr-2">{{ username }}</h3>
                <p class="text-yellow-400 font-bold justify-center mr-4">{{ user_score }} points</p>
            </div>
            <img src="data:image/jpeg;base64,{{ profile_pic }}" alt="Profile Picture" class="w-11 h-11 rounded-full"> <!-- Adjusted here -->
        </li>
             
        {% endfor %}
    </ol>
</div>




{% endblock %}

flask_app/templates/login.html
{% extends "base.html" %}

{% block content %}
<a href="{{ url_for('main.index') }}" class="text-white bg-blue-500 hover:bg-blue-700 font-bold py-2 px-4 rounded">
    Back to Home
</a>
<div class="flex items-center justify-center min-h-screen bg-black">
    <div class="w-full max-w-md p-8 space-y-3 rounded-xl bg-black shadow-lg">
        <h2 class="text-center text-2xl font-bold text-white">Log In</h2>
        <p class="text-center text-gray-300">
            If you don't have an account, <a href="{{ url_for('users.register_route') }}" class="text-blue-400 hover:text-blue-600">register here</a>.
        </p>

        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="p-4 mb-4 text-sm  bg-yellow-200 rounded-lg" role="alert">
            {% for message in messages %}
            <span>{{ message }}</span>
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}

        <!-- Login Form: -->
        <form method="POST" action="{{ url_for('users.login_route') }}" class="space-y-6">
            {{ form.csrf_token }}
            <div class="space-y-1">
                {{ form.username.label(class="block text-sm font-medium text-gray-200") }}
                {{ form.username(class="w-full px-3 py-2 border rounded bg-transparent text-white") }}
                {% if form.username.errors %}
                <div class="text-red-500 text-sm">
                    {{ form.username.errors[0] }}
                </div>
                {% endif %}
            </div>
            <div class="space-y-1">
                {{ form.password.label(class="block text-sm font-medium text-gray-200") }}
                {{ form.password(class="w-full px-3 py-2 border rounded bg-transparent text-white") }}
                {% if form.password.errors %}
                <div class="text-red-500 text-sm">
                    {{ form.password.errors[0] }}
                </div>
                {% endif %}
            </div>
            <div class="flex items-center justify-between">
                <button type="submit" class="w-full py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                    Log In
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

flask_app/templates/loss.html
{% extends "base.html" %} 
{% block content %}
<div class="min-h-screen flex flex-col items-center justify-center bg-black text-white">
    <h1 class="text-4xl font-bold mb-2 text-red-600">You Lost!</h1>
    <p class="text-xl mb-1 bg-gradient-to-r from-yellow-500 to-red-500 text-transparent bg-clip-text">Your current score: {{ lastScore }}</p>
    <p class="text-xl mb-5 bg-gradient-to-r from-yellow-500 to-red-500 text-transparent bg-clip-text">Your highest score: {{ user.highScore }}</p>
    <a href="{{ url_for('main.index') }}" class="bg-blue-500 hover:bg-blue-700 font-bold py-2 px-4 rounded transition duration-300 ease-in-out text-white">
        Back to Home
    </a>
    <a href="{{ url_for('game.leaderboard') }}" class="mt-4 bg-green-500 hover:bg-green-700 font-bold py-2 px-4 rounded transition duration-300 ease-in-out text-white">
        View Leaderboard
    </a>
</div>
{% endblock %}

flask_app/templates/register.html
{% extends "base.html" %}

{% block content %}
<a href="{{ url_for('main.index') }}" class="text-white bg-blue-500 hover:bg-blue-700 font-bold py-2 px-4 rounded">
    Back to Home
</a>
<div class="flex items-center justify-center min-h-screen bg-black">
    <div class="w-full max-w-md p-8 space-y-3 rounded-xl bg-black shadow-lg">
        <h2 class="text-center text-2xl font-bold text-white">Registration</h2>
        <p class="text-center text-gray-300">
            If you already have an account, <a href="{{ url_for('users.login_route') }}" class="text-blue-400 hover:text-blue-600">login here</a>.
        </p>
        
        <!-- Registration Form: -->
        <form method="POST" action="{{ url_for('users.register_route') }}" class="space-y-6">
            {{ form.csrf_token }}
            <div class="space-y-1">
                {{ form.username.label(class="block text-sm font-medium text-gray-200") }}
                {{ form.username(class="w-full px-3 py-2 border rounded bg-transparent text-white") }}
                {% if form.username.errors %}
                <div class="text-red-500 text-sm">
                    {{ form.username.errors[0] }}
                </div>
                {% endif %}
            </div>
            <div class="space-y-1">
                {{ form.email.label(class="block text-sm font-medium text-gray-200") }}
                {{ form.email(class="w-full px-3 py-2 border rounded bg-transparent text-white") }}
                {% if form.email.errors %}
                <div class="text-red-500 text-sm">
                    {{ form.email.errors[0] }}
                </div>
                {% endif %}
            </div>
            <div class="space-y-1">
                {{ form.password.label(class="block text-sm font-medium text-gray-200") }}
                {{ form.password(class="w-full px-3 py-2 border rounded bg-transparent text-white") }}
                {% if form.password.errors %}
                <div class="text-red-500 text-sm">
                    {{ form.password.errors[0] }}
                </div>
                {% endif %}
            </div>
            <div class="space-y-1">
                {{ form.confirm_password.label(class="block text-sm font-medium text-gray-200") }}
                {{ form.confirm_password(class="w-full px-3 py-2 border rounded bg-transparent text-white") }}
                {% if form.confirm_password.errors %}
                <div class="text-red-500 text-sm">
                    {{ form.confirm_password.errors[0] }}
                </div>
                {% endif %}
            </div>
            <div class="flex items-center justify-between">
                <button type="submit" class="w-full py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                    Sign Up
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

flask_app/templates/user.html
{% extends "base.html" %}

{% block content %}
<a href="{{ url_for('main.index') }}" class="text-white bg-blue-500 hover:bg-blue-700 font-bold py-2 px-4 rounded">
    Back to Home
</a>
<div class="container mx-auto py-6 px-4 h-screen flex items-center justify-center">
    <div class="bg-black p-6 rounded-lg shadow-lg max-w-2xl w-full">
        <div class="text-center mb-6 text-white">
            {% if profile_pic_base64 %}
            <img src="data:image/jpeg;base64,{{ profile_pic_base64 }}" alt="Profile Picture" class="mx-auto h-32 w-32 rounded-full mt-4"/>
            {% endif %}
            <h1 class="text-3xl font-bold bg-gradient-to-r from-yellow-500 to-red-500 text-transparent bg-clip-text">Welcome back, {{ user.username }}</h1>
        </div>
        
        <!-- <div class="mb-6">
            <fieldset class="border border-gray-500 p-4 mb-4">
                <legend>
                    <h2 class="text-xl font-semibold mb-2 text-white">Previous Scores</h2>
                </legend>
                <span class="block rounded-full text-white text-xs px-2 py-1 m-1 bg-gray-700">Highscore: {{highscore}}</span>
                <div class="flex flex-wrap justify-center">
                     TODO: Dot Plot / Score Display -->
                     <!--{% for score in scores %}
                    <span class="block rounded-full text-white text-xs px-2 py-1 m-1 bg-gray-700">{{ score }}</span>
                    {% endfor %}
                </div>
            </fieldset>
        </div> -->

        <hr>
        <br>

        <div class="text-white">
            <form method="POST" action="" class="mb-4">
                {{ update_username_form.hidden_tag() }}
                <div class="mb-4">
                    {{ update_username_form.username.label(class="block text-white bg-clip-text text-sm font-bold mb-2") }}
                    {{ update_username_form.username(class="shadow appearance-none border rounded w-full py-2 px-3 bg-transparent text-red-600 leading-tight focus:outline-none focus:shadow-outline") }}
                    {% if update_username_form.username.errors %}
                        <div class="error" role="alert">
                            {% for error in update_username_form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <!-- <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Update Username</button> -->
                {{ update_username_form.submit_username(class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline") }}
            </form>

            <form method="POST" action="" enctype="multipart/form-data">
                {{ update_profile_pic_form.hidden_tag() }}
                <div class="mb-4">
                    {{ update_profile_pic_form.picture.label(class="block text-white text-sm font-bold mb-2") }}
                    {{ update_profile_pic_form.picture(class="form-content shadow appearance-none border bg-transparent rounded w-full py-2 px-3 text-red-600 leading-tight focus:outline-none focus:shadow-outline") }}
                    {% if update_profile_pic_form.picture.errors %}
                        <div class="error" role="alert">
                            {% for error in update_profile_pic_form.picture.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <!-- <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Update Photo</button> -->
                {{ update_profile_pic_form.submit_picture(class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline") }}
            </form>
        </div>

        <div class="text-center mt-6">
            <a href="{{ url_for('users.logout_route') }}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Logout</a>
        </div>
    </div>
</div>

{% endblock %}